# Generated by Django 5.2 on 2025-08-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_profile_forwards(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, height_field='avatar_height', upload_to='user_avatars', width_field='avatar_width')),
                ('avatar_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('avatar_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('avatar_ppoi', models.CharField(default='0.5x0.5', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_profile_forwards),
    ]
