# Generated by Django 4.2 on 2023-04-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, help_text="250 characters long", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="preview_image",
            field=models.ImageField(blank=True, upload_to="category_previews/"),
        ),
        migrations.AddField(
            model_name="categorytag",
            name="description",
            field=models.CharField(
                blank=True, help_text="250 characters long", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="categorytag",
            name="preview_image",
            field=models.ImageField(blank=True, upload_to="tag_previews/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(blank=True, default="", upload_to="blog_previews/"),
            preserve_default=False,
        ),
    ]
