# Generated by Django 4.2 on 2023-04-29 13:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_delete_featuredpost_remove_post_featured_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorytag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag with categories",
                "verbose_name_plural": "Tags with categories",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="Tags, comma separated",
                through="blog.TaggedWithCategoryTags",
                to="blog.CategoryTag",
                verbose_name="Tags with categories",
            ),
        ),
    ]
