# Generated by Django 4.1.7 on 2023-03-24 00:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0003_alter_category_slug_alter_post_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ttags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
