# Generated by Django 4.2 on 2023-05-06 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_categorytag_options_alter_post_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
