# Generated by Django 4.2.2 on 2023-06-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_category_options_category_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_dropdown", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DropdownNavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.category"
                    ),
                ),
                (
                    "parent_nav_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.navitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dropdown Item",
                "verbose_name_plural": "Dropdown Items",
                "ordering": ["order"],
            },
        ),
    ]
