# Generated by Django 4.1.7 on 2023-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_in_menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_front_page",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
