# Generated by Django 4.2.2 on 2023-06-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_navitem_dropdownnavitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navitem",
            name="primary_category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blog.category"
            ),
        ),
    ]
