# Generated by Django 4.1.7 on 2023-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_category_show_in_menu_category_show_on_front_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedPost",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.post",),
        ),
        migrations.AddField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_previews/"),
        ),
    ]
