# Generated by Django 4.1.7 on 2023-04-01 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_featuredpost_post_preview_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="ttags",
            new_name="tags"
        ),
    ]
