# Generated by Django 4.1.7 on 2023-04-02 03:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog", "0009_remove_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="CelebrityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Celebrity tag",
                "verbose_name_plural": "Celebrity tags",
            },
        ),
        migrations.CreateModel(
            name="TaggedWithCelebrities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tags",
                        to="blog.celebritytag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.RemoveField(
            model_name="post",
            name="sub_categories",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
        migrations.AddField(
            model_name="post",
            name="celebrities",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="blog.TaggedWithCelebrities",
                to="blog.CelebrityTag",
                verbose_name="Tags",
            ),
        ),
    ]
