# Generated by Django 4.1.7 on 2023-04-02 12:09

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_celebritytag_taggedwithcelebrities_delete_tag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="celebritytag",
            options={
                "ordering": ["name"],
                "verbose_name": "Celebrity tag",
                "verbose_name_plural": "Celebrity tags",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="is_celebrity_tags",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, this category will link to the celebrity tags list. Only one category should be selected to link to the celebrity tags list.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="celebrities",
            field=taggit.managers.TaggableManager(
                help_text="Celebrities tags, comma separated",
                through="blog.TaggedWithCelebrities",
                to="blog.CelebrityTag",
                verbose_name="Celebrities",
            ),
        ),
    ]
