# Generated by Django 4.2.2 on 2023-09-29 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_categorytag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Please use only letters, numbers, underscores or hyphens; must be unique.",
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
