# Generated by Django 4.2.5 on 2023-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_prevew_image_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_categories",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_sub_category": True},
                related_name="subcat_posts",
                to="blog.categorytag",
            ),
        ),
    ]
