# Generated by Django 4.2.6 on 2023-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_prevew_image_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(
                blank=True, help_text="Used for SEO", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="250 characters long, will also be used in SEO description for the page",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="categorytag",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="250 characters long, can also be used in SEO description for the page",
                max_length=250,
            ),
        ),
    ]
