# Generated by Django 4.2.5 on 2023-10-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_post_sub_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytag",
            name="parent_sub_categories",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_sub_category": True},
                related_name="children_tags",
                to="blog.categorytag",
            ),
        ),
        migrations.AlterField(
            model_name="categorytag",
            name="is_sub_category",
            field=models.BooleanField(
                default=False,
                help_text="⚠ Toggling this will remove this tag from related posts.",
            ),
        ),
    ]
