# Generated by Django 4.2.7 on 2023-11-04 12:23

import django.db.models.deletion
from django.db import migrations, models


def set_default_navdropdownitem_subcategory_forward_func(apps, schema_editor):
    DropdownNavItem = apps.get_model("blog", "DropdownNavItem")
    Subcategory = apps.get_model("blog", "Subcategory")
    default_subcat = Subcategory.objects.first()

    for item in DropdownNavItem.objects.filter(subcategory=None):
        if not default_subcat:
            item.delete()
            continue
        item.subcategory = default_subcat
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_alter_category_options_alter_categorytag_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_default_navdropdownitem_subcategory_forward_func,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="dropdownnavitem",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.subcategory"
            ),
        ),
    ]
