# Generated by Django 4.2.7 on 2023-11-23 13:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_dropdownnavitem_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="Tags, comma separated",
                through="blog.TaggedWithCategoryTags",
                to="blog.CategoryTag",
                verbose_name="Tags",
            ),
        ),
    ]
