# Generated by Django 4.2.7 on 2023-12-02 10:20

from django.db import migrations
import django.db.models.functions.comparison


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorytag",
            options={
                "ordering": [
                    django.db.models.functions.comparison.Collate("slug", "C")
                ],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
