# Generated by Django 5.0.3 on 2024-04-09 11:15

import django.db.models.functions.comparison
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_categorytag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytag',
            options={'ordering': (django.db.models.functions.comparison.Collate('slug', 'C'),), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='featuredpost',
            options={'ordering': ('order', '-post__publish')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
