# Generated by Django 5.2 on 2025-05-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_categorytag_options_alter_featuredpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_post_nav',
            field=models.BooleanField(default=False, help_text='Toggles in-post nav that is linked to headings'),
        ),
    ]
