# Generated by Django 5.2 on 2025-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_show_post_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='preview_image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='preview_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='preview_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='preview_image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='preview_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='show_preview_image',
            field=models.BooleanField(default=True, help_text='Toggles the preview image on the post page only.'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='preview_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='preview_image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='preview_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='preview_image',
            field=models.ImageField(blank=True, height_field='preview_image_height', upload_to='category_previews/', width_field='preview_image_width'),
        ),
        migrations.AlterField(
            model_name='categorytag',
            name='preview_image',
            field=models.ImageField(blank=True, height_field='preview_image_height', upload_to='tag_previews/', width_field='preview_image_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, height_field='preview_image_height', upload_to='blog_previews', width_field='preview_image_width'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='preview_image',
            field=models.ImageField(blank=True, height_field='preview_image_height', upload_to='category_previews/', width_field='preview_image_width'),
        ),
    ]
