# Generated by Django 5.2 on 2025-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_category_preview_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image_position',
            field=models.CharField(choices=[('L', 'Left'), ('T', 'Top')], default='L', help_text='Used to determine the position of the preview image on the post page.', max_length=1),
        ),
    ]
