# Generated by Django 5.2 on 2025-08-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_preview_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('slug',), 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
