# Generated by Django 6.0.2 on 2026-02-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_title',
            field=models.CharField(blank=True, help_text='Used in front page carousel, browser tab title, previews. Full title will be used if left empty.', max_length=250),
        ),
    ]
