# Generated by Django 4.2 on 2023-04-24 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name_plural": "About Page",
            },
        ),
        migrations.CreateModel(
            name="SiteIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="site_identity/")),
                ("favicon", models.ImageField(blank=True, upload_to="site_identity/")),
                ("footer", ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site Identity",
            },
        ),
    ]
