# Generated by Django 4.2 on 2023-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kofi", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Subscription Options",
            },
        ),
    ]
