# Generated by Django 4.2 on 2023-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_subscriptionoptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionoptions",
            name="kofi",
        ),
        migrations.AddField(
            model_name="subscriptionoptions",
            name="kofi_url",
            field=models.URLField(blank=True),
        ),
    ]
