# Generated by Django 4.2 on 2023-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_subscriptionoptions_kofi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "youtube_name",
                    models.CharField(
                        blank=True, help_text="Shown in the mobile menu", max_length=100
                    ),
                ),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "twitter_name",
                    models.CharField(
                        blank=True, help_text="Shown in the mobile menu", max_length=100
                    ),
                ),
            ],
        ),
    ]
