# Generated by Django 4.2 on 2023-05-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_socialmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionoptions",
            name="kofi_account_name",
            field=models.CharField(
                blank=True,
                help_text="Is the name at the end of the URL without the URL stuff",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionoptions",
            name="kofi_url",
            field=models.URLField(
                blank=True, help_text="Should have same account name at the end"
            ),
        ),
    ]
