# Generated by Django 4.2 on 2023-05-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_subscriptionoptions_kofi_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionoptions",
            name="show_kofi_form_in_footer",
            field=models.BooleanField(
                default=False,
                help_text="Shows kofi form in footer, kofi_account_name is used for this widget",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionoptions",
            name="show_kofi_overlay_button",
            field=models.BooleanField(
                default=False,
                help_text="Shows kofi overlap button, kofi_account_name is used for this widget",
            ),
        ),
    ]
