# Generated by Django 4.2 on 2023-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_subscriptionoptions_show_kofi_form_in_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionoptions",
            name="show_kofi_link_in_head_menu",
            field=models.BooleanField(
                default=False,
                help_text="Shows kofi icon and link in the top site menu, kofi_url is used for this link",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionoptions",
            name="show_kofi_overlay_button",
            field=models.BooleanField(
                default=False,
                help_text="Shows kofi overlap button, kofi_account_name is used for this button",
            ),
        ),
    ]
