# Generated by Django 4.2.2 on 2023-06-16 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_subscriptionoptions_kofi_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"verbose_name_plural": "Social Media"},
        ),
    ]
