# Generated by Django 4.2.3 on 2023-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_socialmedia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="header_message",
            field=models.TextField(
                blank=True,
                help_text="Adds a message to the top of the site on all pages. Change to blank to remove the message.",
            ),
        ),
    ]
