# Generated by Django 4.2.5 on 2023-10-03 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_siteidentity_header_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="carousel_logo",
            field=models.FileField(
                blank=True,
                help_text="This logo is used as a placeholder pic for carousel cards. Can be jpg png svg gif, use .svg for best fit, do not upload untrusted files!",
                upload_to="site_identity/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "svg", "gif"]
                    )
                ],
            ),
        ),
    ]
