# Generated by Django 4.2.6 on 2023-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_siteidentity_seo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="seo_keywords",
            field=models.TextField(
                blank=True,
                help_text="List of words in SEO meta tags, eg 'blog, django, python' without quotes",
            ),
        ),
    ]
