# Generated by Django 4.2.7 on 2023-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_siteidentity_logo_siteidentity_logo_square_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteidentity",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                help_text="List of words in SEO meta tags, eg 'blog, django, python' without quotes, comma separated",
                max_length=250,
            ),
        ),
    ]
