# Generated by Django 5.2 on 2025-06-09 10:57

import django_ckeditor_5.fields
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_aboutpage_content_alter_siteidentity_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name_plural': 'Terms of Service',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
