# Generated by Django 5.2 on 2025-07-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_termspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentity',
            name='show_terms_of_service',
            field=models.BooleanField(default=False),
        ),
    ]
