# Generated by Django 5.2 on 2025-07-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_siteidentity_show_terms_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termspage',
            name='title',
            field=models.CharField(default='Terms of Service', max_length=100),
        ),
    ]
