# Generated by Django 5.2 on 2025-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_termspage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentity',
            name='logo_square_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_square_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_square_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_title_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_title_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_title_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteidentity',
            name='logo_square',
            field=models.ImageField(blank=True, height_field='logo_square_height', help_text='Used for seo and other places where a square logo is needed', upload_to='site_identity/', width_field='logo_square_width'),
        ),
        migrations.AlterField(
            model_name='siteidentity',
            name='logo_title',
            field=models.ImageField(blank=True, height_field='logo_title_height', help_text='Used for the main top logo', upload_to='site_identity/', width_field='logo_title_width'),
        ),
    ]
