# Generated by Django 5.2 on 2025-08-12 09:17

import django_ckeditor_5.fields
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_siteidentity_logo_square_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='show_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
