# Generated by Django 5.2 on 2025-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_privacypage_siteidentity_show_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='show_title_in_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='About', max_length=100),
        ),
    ]
