# Generated by Django 5.2 on 2026-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_aboutpage_show_title_in_page_alter_aboutpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='instagram_name',
            field=models.CharField(blank=True, help_text='Shown in the mobile menu', max_length=100),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Leave empty to disable'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Leave empty to disable'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Leave empty to disable'),
        ),
    ]
